#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --file nix \
    distribution.nix-project-exe \
    --command \
    nix-project \
    --source-dir nix/external \
    --nix "$(command -v nix)" \
    init-update \
    "$@"
