#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix shell \
    --ignore-environment \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    .#org2gfm \
    .#nixpkgs.ansifilter \
    .#nixpkgs.coreutils \
    .#nixpkgs.gnugrep \
    .#nixpkgs.gnutar \
    .#nixpkgs.gzip \
    .#nixpkgs.tree \
    --command \
    org2gfm \
    --path-bin \
    --exclude links.org \
    --exclude nix.mac.org \
    --exclude scaffold \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
