#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix shell \
    --ignore-environment \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    .#org2gfm \
    .#nixpkgs.stable.ansifilter \
    .#nixpkgs.stable.coreutils \
    .#nixpkgs.stable.git \
    .#nixpkgs.stable.gnugrep \
    .#nixpkgs.stable.gnutar \
    .#nixpkgs.stable.gzip \
    .#nixpkgs.stable.jq \
    .#nixpkgs.stable.nixfmt-rfc-style \
    .#nixpkgs.stable.tree \
    --command \
    org2gfm \
    --path-bin \
    --exclude internal \
    --exclude example \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
