#+title: Nix-based Project Tools
#+setupfile: doc/internal/links.org

#+ATTR_HTML: :alt built with GitHub Actions
[[https://github.com/shajra/nix-project/actions][https://github.com/shajra/nix-project/workflows/CI/badge.svg]]
#+ATTR_HTML: :alt built with Garnix
[[https://garnix.io/repo/shajra/nix-project][https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fgarnix.io%2Fapi%2Fbadges%2Fshajra%2Fnix-project%3Fbranch%3Dmain]]

* About this project

Nix-project exists to help people use the [[nix][Nix package manager]] to provide the
build, developer tooling, and developer environments for a software project.

Among other benefits, Nix gives us an incredible amount of control and
repeatability of our software projects.  The approach of this project leans
heavily on [[nix-wiki-flakes][flakes]], an experimental Nix feature.

Though Nix-project offers a little library support, it's intended to be
an educational resource providing
- templates you can scaffold projects from
- examples of recommended practices
- lots of documentation to help absolute beginners navigate
  complexities/pitfalls

The custom code in this project supports some actively maintained projects with
- generation of the GitHub-flavored Markdown you're reading now from [[org][Org-mode
  files]].
- slightly augmented functions for authoring scripts beyond what's in [[nixpkgs][Nixpkgs]].

There's not a lot of code in Nix-project. Most of the work is done by Nix and
third-party libraries. If you scaffolded a new project and removed the
dependency on Nix-project, then you'd have a small project set up using Nix with
recommended practices.

This source's [[file:doc][doc directory]] provides a variety of documents to not only help you
use this project, but also to get an introduction to the Nix ecosystem.

If you don't know much about Nix, consider reading the following provided
guides:

- [[file:doc/nix-introduction.org][Introduction to Nix and Motivations to Use It]]
- [[file:doc/nix-installation.org][Nix Installation and Configuration Guide]]
- [[file:doc/nix-usage-flakes.org][Nix End-user Guide]]
- [[file:doc/nix-language.org][Introduction to the Nix Programming Language]]

If you already know Nix basics, then these documents will help you get started
with a Nix-based project:

- [[file:doc/project-developing-basics.org][Flakes Basic Development Guide]]
- [[file:doc/project-developing-modules.org][Flake Module (with =flake-parts=) Development Guide]]
- [[file:doc/project-documenting.org][Documenting a Nix Project with Nix-project]]

* Release

The "main" branch of the GitHub repository has the latest released version of
this code. There is currently no commitment to either forward or backward
compatibility.

"user/shajra" branches are personal branches that may be force-pushed. The
"main" branch should not experience force-pushes and is recommended for general
use.

* License

All files in this "nix-project" project are licensed under the terms of GPLv3 or
(at your option) any later version.

Please see the [[./COPYING.md][./COPYING.md]] file for more details.

* Contribution

Feel free to file issues and submit pull requests with GitHub.

There is only one author to date, so the following copyright covers all files in
this project:

Copyright © 2019 Sukant Hajra
