#+title: Nix-based Project Tools
#+setupfile: doc/internal/links.org

[[https://github.com/shajra/nix-project/actions][https://github.com/shajra/nix-project/workflows/CI/badge.svg]]

* About this project

This project, Nix-project, assists the setup of other projects with the [[nix][Nix
package manager]] leaning on [[nix-flake][flakes]], an experimental Nix feature.

Specifically, this project helps

- scaffold new projects
- maintain dependencies, which may mix different language ecosystems
- generate Github-oriented documentation with evaluated code blocks
- build and distribute packages, binary or otherwise.

This source's [[file:doc][doc directory]] provides a variety of documents to not only help you
use this project, but to also get an introduction to the Nix ecosystem.

Among other benefits, Nix gives use an incredible amount of control and
repeatability of our software projects. If you don't know much about Nix,
consider reading the following:

- [[file:doc/nix-introduction.org][Introduction to Nix and motivations to use it]]
- [[file:doc/nix-installation.org][Nix installation and configuration guide]]
- [[file:doc/nix-usage-flakes.org][Nix end user guide with flakes]]
- [[file:doc/nix-usage-noflakes.org][Nix end user guide without flakes]]
- [[file:doc/nix-language.org][Introduction to the Nix programming language]]

If you know something about Nix, then these documents will help you get started
using this project:

- [[file:doc/project-developing.org][Developing a Nix project with Nix-Project]]
- [[file:doc/project-documenting.org][Documenting a Nix project with Nix-project]]

* Release

The "main" branch of the repository on GitHub has the latest released version
of this code. There is currently no commitment to either forward or backward
compatibility.

"user/shajra" branches are personal branches that may be force-pushed to. The
"main" branch should not experience force-pushes and is recommended for
general use.

* License

All files in this "nix-project" project are licensed under the terms of GPLv3 or
(at your option) any later version.

Please see the [[./COPYING.md][./COPYING.md]] file for more details.

* Contribution

Feel free to file issues and submit pull requests with GitHub.

There is only one author to date, so the following copyright covers all files in
this project:

Copyright © 2019 Sukant Hajra
