((package-attr    . "nix-project-exe")
 (package-name    . "nix-project")
 (package-type    . "executable")
 (package-target  . "nix-project")
 (run-file        . ".")
 (run-attr        . "nix-project-exe")
 (run-name        . "nix-project")
 (run-target      . "nix-project"))
