#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --file '@NIV_DIR@' \
    nix-project.nix-project-exe \
    --command \
    nix-project \
    --source-dir '@NIV_DIR@' \
    --nix "$(command -v nix)" \
    init-update \
    "$@"
