#!/bin/sh -eu

cd "$(dirname "$0")/.."

# DESIGN: the `coreutils` argument makes utilities like `whoami` available for
# evaluated code blocks. This is just an example, you can include any package
# you like.
nix run \
    --ignore-environment \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    --file '@NIV_DIR@' \
    nix-project.nix-project-org2gfm \
    nixpkgs.coreutils \
    --command \
    org2gfm \
    --path-bin \
    --evaluate \
    "$@"
