name: "CI"
on:
  push:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31.6.0
      with:
        # DESIGN: matching current in NixOS 25.05
        install_url: https://releases.nixos.org/nix/nix-2.28.4/install
    - uses: cachix/cachix-action@v16
      with:
        name: shajra
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - uses: DeterminateSystems/flakehub-cache-action@main
    - run: cat /etc/nix/nix.conf
    - run: cat ~/.config/nix/nix.conf
    - run: nix --print-build-logs flake check --verbose
